## OOP Concepts
1. Encapsulation
2.Inheritance
3.Polymorphism
4.Abstraction


## Inheritance
1. single
2.Multi-level
3.Multiple
4.Hierarchical
5.Hybrid

In [ ]:
#Single
class parent:
    def Pfun(self):
        print("Parent Class")
class Child:
    def Cfun(self):
        print("Child Class")
ob=Child()
ob.Cfun()
    

In [ ]:
#Single
class parent:
    def Pfun(self):
        print("Parent Class")
class Child:
    def Cfun(self):
        print("Child Class")
ob=Child()
ob.Pfun()
    

In [ ]:
#Single
class parent:
    def Pfun(self):
        print("Parent Class")
class Child(parent): # inheritance
    def Cfun(self):
        print("Child Class")
ob=Child()
ob.Pfun()
    

In [ ]:
#Multi-level
class Gparent:
    def Gfun(self):
        print("Grand Parent Class")
class parent(Gparent):    
    def Pfun(self):
        print("Parent Class")
class Child(parent):
    def Cfun(self):
        print("Child Class")
ob=Child()
ob.Pfun()
ob.Gfun()
  # we can call multiple ob by single  

In [ ]:
class Gparent:
    def Gfun(self):
        print("Grand Parent Class")
class parent(Gparent):    
    def Pfun(self):
        print("Parent Class")
class Child(parent):
    def Cfun(self):
        print("Child Class")
ob=Gparent()
#ob.Pfun()
ob.Gfun()

In [5]:
class Gparent:
    def fun(self):
        print("Grand Parent Class")
class parent(Gparent):    
    def fun(self):
        
        print("Parent Class")
class Child(parent):
    def Cfun(self):
        print("Child Class")
ob=Child()
#ob.Pfun()
ob.fun()

Parent Class


In [3]:
class Gparent:
    def fun(self):
        print("Grand Parent Class")
class parent(Gparent):    
    def fun(self):
        super().fun()
        print("Parent Class")
class Child(parent):
    def Cfun(self):
        print("Child Class")
ob=Child()
ob.fun()

Grand Parent Class
Parent Class


In [1]:
# it is also call method overiding using super

class Gparent:
    def fun(self):
        print("Grand Parent Class")
class parent(Gparent):    
    def fun(self):
        super().fun()
        print("Parent Class")
class Child(parent):
    def fun(self):
        super().fun()
        print("Child Class")
ob=Child()
ob.fun()

Grand Parent Class
Parent Class
Child Class


In [7]:
# Hierarchical
class parent():    
    def fun(self):
       
        print("Parent Class")
class Child1(parent):
    def Cfun(self):
       
        print("Child1 Class")
class Child2(parent):
    def Cfun(self):
       
        print("Child2 Class")
ob=Child1()
ob.fun()
ob.Cfun()
# use child 2 we make object of it

ob=Child2()

ob.Cfun()



Parent Class
Child1 Class
Child2 Class


In [9]:
# Multiple


class parent1:
    def fun1(self):
        print("Parent1 Class")
class parent2:                 # no link betw parent1 and p2
    def fun2(self):
        print("Parent2 Class")
class Child(parent1,parent2):
    def fun(self):
        print("Child Class")
ob=Child()
ob.fun()
ob.fun1()
ob.fun2()

Child Class
Parent1 Class
Parent2 Class


In [11]:
class parent1:
    def fun(self):
        print("Parent1 Class")
class parent2:                 
    def fun(self):
        print("Parent2 Class")
class Child(parent1,parent2):
    def fun1(self):
        print("Child Class")
ob=Child()
ob.fun()
ob.fun1()


Parent1 Class
Child Class


In [13]:
class parent1:
    def fun(self):
        print("Parent1 Class")
class parent2:                 
    def fun(self):
        print("Parent2 Class")
class Child(parent1,parent2):    # left side always go search
    def fun(self):
        print("Child Class")
ob=Child()
ob.fun()



Child Class


In [15]:
class parent1:
    def fun(self):
        print("Parent1 Class")
class parent2:                 
    def fun(self):
        print("Parent2 Class")
class Child(parent1,parent2):
    def fun(self):
        print("Child Class")
        super().fun()
        super().fun() # drawback
ob=Child()
ob.fun()

Child Class
Parent1 Class
Parent1 Class


In [17]:
class parent1:
    def fun(self):
        print("Parent1 Class")
class parent2:                 
    def fun(self):
        print("Parent2 Class")
class Child(parent1,parent2):
    def fun(self):
        print("Child Class")
        super().fun() # only control on parent
        super().fun()
ob=Child()
ob.fun()
print(Child.__mro__) # left most parent to right 

Child Class
Parent1 Class
Parent1 Class
(<class '__main__.Child'>, <class '__main__.parent1'>, <class '__main__.parent2'>, <class 'object'>)


In [19]:
class parent1:
    def fun(self):
        print("Parent1 Class")
class parent2:                 
    def fun(self):
        print("Parent2 Class")
class Child(parent1,parent2):
    def fun(self):
        print("Child Class")
        super().fun() 
        parent2.fun(self)    # alternate   to access parent2  with class
ob=Child()
ob.fun()
print(Child.__mro__)

Child Class
Parent1 Class
Parent2 Class
(<class '__main__.Child'>, <class '__main__.parent1'>, <class '__main__.parent2'>, <class 'object'>)


## Method Resolution Order
* Left to Right Search
* DFS

In [ ]:
class A:
    def test1(self):
        print(" test of A called ")
class B(A):
    def test(self):
        print(" test of B called ") # find so not go ahead
class C(A):
    def test(self):
        print(" test of C called ")
class D(B,C):
    def test2(self):
        print(" test of D called ")        
obj=D()
obj.test()
print(D.__mro__)

In [ ]:
class A:
    def rk(self):
        print(" In class A")
class B:
    def rk(self):
        print(" In class B")
class C(A, B):
    def rk(self):
        pass
r = C()
print(C.__mro__)

In [ ]:
class A:
    pass
class B:
    pass
class C:
    pass
class X(B):
    pass
class Y(C,A,B):
    pass
class Z(A):
    pass
class P(Z,Y,X):
    pass
print(P.__mro__)

In [ ]:
class A:
    pass
class B:
    pass
class C:
    pass
class X(A,B):
    pass
class Y(C,A,B):
    pass
class Z(A):
    pass
class P(Z,Y,X):
    pass
print(P.__mro__)

In [ ]:
class A:
    pass
class B:
    pass
class C:
    pass
class X(B,A): #  not possible 
    pass
class Y(C,A,B): # not possible bcz order is not same
    pass
class Z(A):
    pass
class P(Z,Y,X):
    pass
print(P.__mro__)

In [ ]:
class P:
    pass
class Q:
    pass
class R(P,Q):
    pass
class S(Q):
    pass     
class T(S,R):
    pass
a=T()
T.__mro__

In [ ]:
class A: pass
class B: pass
class C: pass
class D:pass
class E:pass
class K1(C,A,B): pass
class K3(A,D): pass
class K2(B,D,E): pass
class Z( K1,K3,K2): pass
Z.__mro__

In [ ]:
class A: pass
class B: pass
class C(A): pass
class D(B):pass
class E(C,D):pass
class S:pass
ob=E()
print(issubclass(A,E))
print(issubclass(E,A))# 1st argument child ,2nd argument parent


In [ ]:
print(isinstance(ob,E)) # bcz all inheritance in E hybrid all mul level
print(isinstance(ob,S))

In [ ]:
class A: pass
class B: pass
class C(A): pass
class D(B):pass
class E(C,D):pass
ob=C()
print(isinstance(ob,B))# not related 
print(isinstance(ob,A)) # related with c

In [ ]:
l=[10,"b",100]

for i in l:
    if isinstance(i,str):
        print(i*2)
    elif isinstance(i,int):
        print(i+5)
    
        
    

# 633

In [ ]:
class staff:
    def __init__(self,n,sal):
        self.name=n
        self.sal=sal
class Tech(staff):
    def __init__(self,n,sal,sub):
        super().__init__(n,sal)
        self.sub=sub
    def Dis(self):
        print("Name:",self.name)
        print("Salary:",self.sal)
        print("Subject",self.sub)
class NonTech(staff):
    def __init__(self,n,sal,dept):
        super().__init__(n,sal)
        self.dept=dept
    def Dis(self):
        print("Name:",self.name)
        print("Salary:",self.sal)
        print("Department",self.dept)
ob1=Tech("A",500,"Java")
ob1.Dis()
ob2=NonTech("B",700,"IT")
ob2.Dis()
    

# Polymorphism
1. Method Overriding
2. Operator Overloading

In [ ]:
# Method Overloading
class A:
    def test(self,a,b):# Overriding
        print("First test")
    def test(self,a):   # Overriding
        print("Second test")
    def test(self):
        print("Third test")
ob=A()
#ob.test(10)
ob.test()
    

In [21]:
# Operator Overloading
class Point:
    def __init__(self,x):
        self.x=x
o1=Point(5)
o2=Point(10)
print(o1+o2)
#unsupported operand type(s) for +: 'Point' and 'Point' in ---->>>>OBJECT!!!!!!


TypeError: unsupported operand type(s) for +: 'Point' and 'Point'

In [ ]:
# Operator Overloading
class Point:
    def __init__(self,x):
        self.x=x
    def __add__(self,other):# compalsory to take 2 parameter when use operater like + use parameter like any other ,ot etc.
        return self.x + other.x
o1=Point(5)
o2=Point(10)
print("Addition",o1+o2)

In [ ]:
class Point:
    def __init__(self,x):
        self.x=x
    def __add__(self,other):# compalsory to take 2 parameter when use operater like + use parameter like any other ,ot etc.
        return self.x * other.x
o1=Point(5)
o2=Point(10)
print("Addition",o1+o2)

In [ ]:
class Point:
    def __init__(self,x):
        self.x=x
    def __add__(self,other):# compalsory to take 2 parameter when use operater like + use parameter like any other ,ot etc.
        return self.x + other.x
o1=Point(5)
o2=Point(10)
print("Addition",o1+o2)
print("Addition",o1-o2) # bcz not use sub

In [23]:
class Point:
    def __init__(self,x):
        self.x=x
    def __add__(self,other):
        return self.x + other.x
    def __sub__(self,other):
        return self.x - other.x
    def __mul__(self,other):
        return self.x * other.x
    def __truediv__(self,other):
        return self.x / other.x
    def __floordiv__(self,other):
        return self.x // other.x
    def __mod__(self,other):
        return self.x % other.x
    def __pow__(self,other):
        return self.x ** other.x
    
    def __lt__(self,o):
        if self.x<o.x:
            print(self.x,"is less than ",o.x)
        else:
            print(o.x,"is less than",self.x)
    
o1=Point(5)
o2=Point(10)
print("Addition",o1+o2)
print("sub",o1-o2)
print("mul",o1*o2)
print("truediv",o1/o2)
print("floordiv",o1//o2)
print("mod",o1%o2)
print("pow",o1**o2)
o1<o2


Addition 15
sub -5
mul 50
truediv 0.5
floordiv 0
mod 5
pow 9765625
5 is less than  10


In [ ]:
class Point:
    def __init__(self,x):  # here only (x)1 value that why it run if y give  
        self.x=x
    def __add__(self,other):
        return Point (self.x + other.x)
o1=Point(5)
o2=Point(10)
o3=Point(2)
o4=Point(5)
ss=o1+o2      #
s=o1+o2+o3+o4    # o3,o4 going self 
print(s.x)
print(ss.x)




#  637 638

# 641

In [ ]:
class student:
    def __init__(self,roll,name,age,tmark):
        self.roll=roll
        self.name=name
        self.age=age
        self.tmark=tmark
    def __eq__(self,other):
         if self.tmark==other.tmark:
            print(self.name,"is equal ",other.name)
         else:
                print(other.name,"not equal",self.name)
o1=student(1,"dev",15,50)
o2=student(2,"jay",16,50)
print(o1==o2)
        

In [25]:
class student:
    s=[]
    def __init__(self,rno,name,age,total):
        self.rno=rno
        self.name=name
        self.age=age
        self.total=total
        student.s.append(self)
    def __eq__(self,other):
         if self.total==other.total:
                print(self.name,"has same mark as ",other.name)
o1=student(1,"dev",15,50)
o2=student(2,"jay",16,50)
o3=student(3,"pooja",17,51)
o4=student(4,"rahul",21,51)
for i in range(len(student.s)):
    for j in range(i+1,len(student.s)):# st with next for comparing so i+1 TO stop compare same one
        student.s[i]==student.s[j]


dev has same mark as  jay
pooja has same mark as  rahul


In [ ]:
# 442

In [ ]:
class student:
    s=[]
    def __init__(self,rno,name,age,total):
        self.rno=rno
        self.name=name
        self.age=age
        self.total=total
        student.s.append(self)
    def __gt__(self,o):
         if self.total>o:  # we can also campare as object and as a value 
                print(self.name,self.rno,self.age,self.total)
o1=student(1,"A",15,85)
o2=student(2,"B",16,80)
o3=student(3,"C",17,85)
o4=student(4,"D",21,82)
o5=student(5,"E",22,80)
for i in range(len(student.s)):
    student.s[i]>80              # like we assign  80 as a specified value


# Abstraction
* from abc import ABC

In [ ]:
from abc import ABC
class Demo (ABC):
    pass 
class A(Demo):
    def dis(self):
        print("Abstraction Example")
ob=Demo()
#ob.dis()

In [ ]:
from abc import ABC,abstractmethod
class Demo (ABC):
    @abstractmethod # must use decorater
    def dis(self):
        pass 
class A(Demo):
    def dis(self):
        print("Abstraction Example")
ob=A()


In [ ]:
from abc import ABC,abstractmethod
class Demo (ABC):
    @abstractmethod # must use decorater
    def dis(self): # this is only abst
        pass 
    def f1(self):
        print("fun1")
        
    def f2(self):
        print("fun2")
class A(Demo):
    def dis(self):
        print("Abstraction Example")
ob=A()
ob.dis()
ob.f1()
ob.f2()


In [ ]:
from abc import ABC,abstractmethod
class Demo (ABC):
    @abstractmethod # must use decorater
    def dis(self): # this is only abst
        pass 
    def f1(self):
        print("fun1")
    @abstractmethod
        
    def f2(self):
        print("fun2")
class A(Demo):
    def dis(self):      # must implement the @abstractmethod if not give error
        print("Abstraction Example")
    def f2(self,a):
        print("fun2",a)
ob=A()
ob.dis()
ob.f1()
ob.f2(10)


In [ ]:
from abc import ABC,abstractmethod
class shape(ABC):
    @abstractmethod
    def calculate_area(self):
            pass
class Rectangle:
    r=[]
    def calculate_area(self,l,b):
        return l*b
class circle:
    c=[]
    def calculate_area(self,r):
        return r**2*3.14
ob=Rectangle()
print(ob.calculate_area(5,5))
ob1=circle()
print(ob1.calculate_area(5))    

In [ ]:
from abc import ABC,abstractmethod
class shape(ABC):
    @abstractmethod
    def calculate_area(self):
            pass
class Rectangle(shape):
    
    def __init__(self,l,b):
        self.l=l
        self.b=b
    def calculate_area(self):
        self.area_of_rectangle=(self.l*self.b)
        print("Area rect",self.area_of_rectangle)
    def __gt__(self,o):
        if (self.area_of_rectangle>o.area_of_rectangle): 
            print("less")
        else:
            print("Greater")
        
    
class circle:
    def __init__(self,r):
        self.r=r
    def calculate_area(self):
        self.area_of_circle=(self.r**2*314)
        print("Area of circle", self.area_of_circle)
    def __gt__(self,o):
        if (self.area_of_circle>o.area_of_circle):
            print("c1 gt than c2")
        else:
            print("c2 gt than c1")
 
   
    
        
ob=Rectangle(1,1)
ob.calculate_area()
ob1=Rectangle(5,5)
ob1.calculate_area()
ob>ob1


obc1=circle(1)
obc1.calculate_area()
obc2=circle(2)
obc2.calculate_area()
obc1>obc2

# 653

In [ ]:
#653
from abc import ABC,abstractmethod
import math
class Shape(ABC):
    @abstractmethod
    def calculate_area(self):
        pass
    
class Rectangle(Shape):
    def __init__(self,l,b):
        self.l=l
        self.b=b
        
    def calculate_area(self):
        self.area_of_rectangle = (self.l * self.b)
        print("Area of rectangle: ",self.area_of_rectangle)
        
    def __gt__(self,o):
        if self.area_of_rectangle >o.area_of_rectangle:
            print("Rect1 has greater area than Rect2")
        else:
            print("Rect2 has greater area than Rect1")
        
class Circle(Shape):
    def __init__(self,r):
        self.r=r
        
    def calculate_area(self):
        self.area_of_circle =(math.pi*self.r)**2
        print("Area of circle: ",self.area_of_circle)
 
rect1 = Rectangle(10,20)
rect2 = Rectangle(5,2)
rect1.calculate_area()
rect2.calculate_area()
rect1>rect2
print("---------------------------------------------")
c1 = Circle(5)
c1.calculate_area()
print(Circle.__mro__)

In [1]:
#653
from abc import ABC,abstractmethod

class Shape(ABC):
    @abstractmethod
    def calculate_area(self):
        pass
    
class Rectangle(Shape):
    def __init__(self,l,b):
        self.l=l
        self.b=b
        
    def calculate_area(self):
        self.area_of_rectangle = (self.l * self.b)
        print("Area of rectangle: ",self.area_of_rectangle)
        
    def __gt__(self,o):
        if self.area_of_rectangle >o.area_of_rectangle:
            print("Rect1 has greater area than Rect2")
        else:
            print("Rect2 has greater area than Rect1")
        
class Circle(Shape):
    def __init__(self,r):
        self.r=r
        
    def calculate_area(self):
        self.area_of_circle =(3.14*self.r)**2
        print("Area of circle: ",self.area_of_circle)
    def __gt__(self,ot):
        if self.area_of_circle>ot.area_of_circle:
            print("c1 gt than c2")
        else:
            print("c2 gt than c1")
 
rect1 = Rectangle(10,20)
rect2 = Rectangle(5,2)
rect1.calculate_area()
rect2.calculate_area()
rect1>rect2
print("---------------------------------------------")
c1 = Circle(5)
c1.calculate_area()
c2 = Circle(10)
c2.calculate_area()
c1>c2
print(Circle.__mro__)

Area of rectangle:  200
Area of rectangle:  10
Rect1 has greater area than Rect2
---------------------------------------------
Area of circle:  246.49000000000004
Area of circle:  985.9600000000002
c2 gt than c1
(<class '__main__.Circle'>, <class '__main__.Shape'>, <class 'abc.ABC'>, <class 'object'>)


# 651

In [1]:
#651
from abc import ABC, abstractmethod
class Employee(ABC):
    @abstractmethod
    def receive_call(self):
        pass
  
    @abstractmethod
    def end_call(self):
        pass
    @abstractmethod
    def is_free(self):
        pass
  
    @abstractmethod
    def get_rank(self):
        pass
    
class Respondent(Employee):
    def __init__(self,id,name):
        self.id=id
        self.name=name
        self.rank=3
        self.free=True
        
    def receive_call(self):
        print("Call received by",self.name)
        self.free=False
        
    def end_call(self):
        print("Call ended")
        self.free=True
        
    def is_free(self):
        return self.free
    
    def get_rank(self):
        return self.rank
    
class Manager(Employee):
    def __init__(self,id,name):
        self.id=id
        self.name=name
        self.rank=2
        self.free=True
        
    def receive_call(self):
        print("Call received by",self.name)
        self.free=False
        
    def end_call(self):
        print("Call ended")
        self.free=True
        
    def is_free(self):
        return self.free
    
    def get_rank(self):
        return self.rank
    
class Director(Employee):
    def __init__(self,id,name):
        self.id=id
        self.name=name
        self.rank=1
        self.free=True
        
    def receive_call(self):
        print("Call received by",self.name)
        self.free=False
        
    def end_call(self):
        print("Call ended")
        self.free=True
        
    def is_free(self):
        return self.free
    
    def get_rank(self):
        return self.rank
class Call:
    def __init__(self,Id,name):
        self.Id=Id
        self.name=name
        self.assigned = False
    
class CallHandler:
    res=[]
    manager=[]
    director=[]
    
    def add_employee(self,ob):
        if ob.rank==1:
            CallHandler.director.append(ob)
        elif ob.rank==2:
            CallHandler.manager.append(ob)
        elif ob.rank==3:
            CallHandler.res.append(ob)
            
    def dispatch_call(self,call):
        for i in CallHandler.res:
            if i.is_free():
                i.receive_call()
                call.assigned = True
                break
        else:
            for i in CallHandler.manager:
                if i.is_free():
                    i.receive_call()
                    call.assigned = True
                    break
            else:
                for i in CallHandler.director:
                    if i.is_free():
                        i.receive_call()
                        call.assigned = True
                        break
                else:
                    print("Sorry! All employees are currently busy.")
                    
R1 = Respondent(1,"R1")
R2 = Respondent(2,"R2")
R3 = Respondent(3,"R3")

M1 = Manager(11,"M1")
M2 = Manager(12,"M2")

D1 = Director(100,"D1")

ch = CallHandler()
ch.add_employee(R1)
ch.add_employee(R2)
ch.add_employee(R3)
ch.add_employee(M1)
ch.add_employee(M2)
ch.add_employee(D1)

C1 = Call(101,"Ram")
C2 = Call(102,"Rama")
C3 = Call(103,"Aham")
C4 = Call(104,"Alice")
C5 = Call(105,"Zyan")
C6 = Call(106,"Charles")
C7 = Call(107,"Olivia")
C8 = Call(108,"Arjun")


ch.dispatch_call(C1)
ch.dispatch_call(C2)
ch.dispatch_call(C3)
ch.dispatch_call(C4)
ch.dispatch_call(C5)
ch.dispatch_call(C6)
ch.dispatch_call(C7)
ch.dispatch_call(C8)

Call received by R1
Call received by R2
Call received by R3
Call received by M1
Call received by M2
Call received by D1
Sorry! All employees are currently busy.
Sorry! All employees are currently busy.


# Numpy

In [27]:
import numpy  as np
arr=np.array(list)

print(arr)
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [29]:
import numpy  as np
arr=np.array(tuple)

print(arr)
print(type(arr))

<class 'tuple'>
<class 'numpy.ndarray'>


In [31]:
import numpy  as np
arr=np.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
import numpy  as np
arr=np.array([1,2.1,3])
print(arr)
print(type(arr))

In [3]:
import numpy  as np
arr=np.array(["a,b,c"])
print(arr)
print(type(arr))

['a,b,c']
<class 'numpy.ndarray'>


In [33]:
a=np.array(10)
print(a)
print("Dimension:",a.ndim)
print(a.shape)


10
Dimension: 0
()


In [35]:
a=np.array([10,20,30])# multiple value make Dimension: 1
print(a)
print("Dimension:",a.ndim)
print(a.shape)

[10 20 30]
Dimension: 1
(3,)


In [37]:
a=np.array([[1,2],[3,4],[5,6]])  # conti [[ open2
print(a)
print("Dimension:",a.ndim)
print(a.shape)

[[1 2]
 [3 4]
 [5 6]]
Dimension: 2
(3, 2)


In [ ]:
a=np.array([[1,2,15],[3,4],[5,6]])  # not make
print(a)
print("Dimension:",a.ndim)
print(a.shape)

In [ ]:
a=np.array([[1,2,15],[3,4,5],[5,6,8]])  
print(a)
print("Dimension:",a.ndim)
print(a.shape)

In [ ]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])  
print(a)
print("Dimension:",a.ndim)
print(a.shape)

In [ ]:
y=np.array([1,2,3],ndmin=6)
print(y)
print(y.shape)


In [ ]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]],ndmin=10)  
print(a)
print("Dimension:",a.ndim)
print(a.shape)

In [ ]:
a=np.array([1,2,3,4,5,6])
#print(a)
y=a.reshape(3,2)
print(y)

In [41]:
a=np.array([1,2,3,4,5,6])

y=a.reshape(2,3,1)
print(y)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [39]:
a=np.array([1,2])#2*1<len(arr)

y=a.reshape(2,3,1)
print(y)

ValueError: cannot reshape array of size 2 into shape (2,3,1)

In [ ]:
a=np.array([1,2,3,4,5,6])# not sufficient value  2*3*3>len (arr)

y=a.reshape(2,3,3)
print(y)

In [5]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])

y=a.reshape(2,3,3)
print(y)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [ ]:
a=np.array([1,2,3,4])

y=a.reshape(2,-1,2)
print(y)

In [ ]:
a=np.array([1,2,3,4])

y=a.reshape(-1,2,2)
print(y)

In [ ]:
a=np.array([1,2,3,4])

y=a.reshape(2,2,-1)
print(y)

In [ ]:
a=np.array([1,2,3,4,5,6])

y=a.reshape(6)
print(y)

In [43]:
a=np.array([1,2,3,4,5,6])

y=a.reshape(-1) #alternate we value is unknow
print(y)

[1 2 3 4 5 6]


In [ ]:
a=np.array(range(1,145))
print(a)
y=a.reshape(3,4,2,6)
print(y)

In [ ]:
a=np.array(range(1,145))
#print(a)
y=a.reshape(-1)
print(y)

In [ ]:
a=np.array(range(1,65))
#print(a)
y=a.reshape(2,4,8)
print(y)

# NumpPy Array Iterating

In [4]:
#Iterating 1D Arrays
import numpy as np
arr = np.array([1,2,3])
for x in range (len(arr)):
    print(arr)



[1 2 3]
[1 2 3]
[1 2 3]


In [12]:
arr = np.array(range(1,13)).reshape(2,3,2)
print(arr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [14]:
for M in arr:
    print(M)
    print("******")
    

[[1 2]
 [3 4]
 [5 6]]
******
[[ 7  8]
 [ 9 10]
 [11 12]]
******


In [16]:
for M in arr:
    print(M[0])
    print("******")

[1 2]
******
[7 8]
******


In [18]:
for M in range (len(arr)):
    for row in range(len(arr[M])):
        arr[M][row][1]*=10
        
   
    print(arr)
    

[[[ 1 20]
  [ 3 40]
  [ 5 60]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[  1  20]
  [  3  40]
  [  5  60]]

 [[  7  80]
  [  9 100]
  [ 11 120]]]


In [20]:
import numpy as np
arr = np.array(range(1,25)).reshape(4,3,2)
print(arr)
#2,6,14,18

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


In [22]:
for M in range (0,len(arr),2):
    for row in range(0,len(arr[M]),2):
        arr[M][row][1]*=10
        
   
    print(arr)

[[[ 1 20]
  [ 3  4]
  [ 5 60]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]
[[[  1  20]
  [  3   4]
  [  5  60]]

 [[  7   8]
  [  9  10]
  [ 11  12]]

 [[ 13 140]
  [ 15  16]
  [ 17 180]]

 [[ 19  20]
  [ 21  22]
  [ 23  24]]]


In [ ]:
# iterating 2D array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(x)

# Slicing NumPy Array:
* Slicing in python means taking elements from one given index to another given index.
* [start: end: step]
* If we don't pass start it's considered O
* If we don't pass end it's considered length of array in that dimension
* If we don't pass step it's considered 1

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr[1:5])

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1::2])

In [24]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [11]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1:3,1:4])   #arr[row_start : row_end , col_start : col_end]

[[7 8 9]]


In [13]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[16,17,18,19,20]])# take 1 and 2 as 1:3 after 1
print(arr[1:3,1:4])  #arr[row_start : row_end , col_start : col_end]

[[ 7  8  9]
 [17 18 19]]


In [15]:
# ::2 → take every 2nd row (row 0, row 2)
# ::3 → take every 3rd column (column 0, column 3)
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[16,17,18,19,20]])
print(arr[::2,::3])

[[ 1  4]
 [16 19]]


In [30]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[16,17,18,19,20]])
print(arr[1:3,::-2])

[[10  8  6]
 [20 18 16]]


In [32]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[16,17,18,19,20]])
print(arr[1:3,::-1])

[[10  9  8  7  6]
 [20 19 18 17 16]]


In [34]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[16,17,18,19,20]])
print(arr[1:3,::-3])

[[10  7]
 [20 17]]


In [9]:
import numpy as np
arr =np.array(range(1,41)).reshape(5,8)
print(arr)


[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]]


In [40]:
arr[:,2::3]

array([[ 3,  6],
       [11, 14],
       [19, 22],
       [27, 30],
       [35, 38]])

In [42]:
arr[::3,1::3]

array([[ 2,  5,  8],
       [26, 29, 32]])

In [52]:
import numpy as np
arr =np.array(range(1,241)).reshape(5,8,6)
print(arr)

[[[  1   2   3   4   5   6]
  [  7   8   9  10  11  12]
  [ 13  14  15  16  17  18]
  [ 19  20  21  22  23  24]
  [ 25  26  27  28  29  30]
  [ 31  32  33  34  35  36]
  [ 37  38  39  40  41  42]
  [ 43  44  45  46  47  48]]

 [[ 49  50  51  52  53  54]
  [ 55  56  57  58  59  60]
  [ 61  62  63  64  65  66]
  [ 67  68  69  70  71  72]
  [ 73  74  75  76  77  78]
  [ 79  80  81  82  83  84]
  [ 85  86  87  88  89  90]
  [ 91  92  93  94  95  96]]

 [[ 97  98  99 100 101 102]
  [103 104 105 106 107 108]
  [109 110 111 112 113 114]
  [115 116 117 118 119 120]
  [121 122 123 124 125 126]
  [127 128 129 130 131 132]
  [133 134 135 136 137 138]
  [139 140 141 142 143 144]]

 [[145 146 147 148 149 150]
  [151 152 153 154 155 156]
  [157 158 159 160 161 162]
  [163 164 165 166 167 168]
  [169 170 171 172 173 174]
  [175 176 177 178 179 180]
  [181 182 183 184 185 186]
  [187 188 189 190 191 192]]

 [[193 194 195 196 197 198]
  [199 200 201 202 203 204]
  [205 206 207 208 209 210]
  [211 212 2

In [54]:
arr[:,0,1:3]

array([[  2,   3],
       [ 50,  51],
       [ 98,  99],
       [146, 147],
       [194, 195]])

In [56]:
arr[0::3,0::7,2]

array([[  3,  45],
       [147, 189]])

In [58]:
arr[0::3,0::7,2:3] # slicing save dimension by cut bcz 2:3 means only 2 ,3last not count  

array([[[  3],
        [ 45]],

       [[147],
        [189]]])

In [60]:
 arr[0::3,0:7:,2:3]

array([[[  3],
        [  9],
        [ 15],
        [ 21],
        [ 27],
        [ 33],
        [ 39]],

       [[147],
        [153],
        [159],
        [165],
        [171],
        [177],
        [183]]])

In [62]:
arr[1::3,0::7,5:6]

array([[[ 54],
        [ 96]],

       [[198],
        [240]]])

In [46]:
import numpy as np
arr1=np.array ([[1,3], [14,20], [5,6]])
arr2=np.array ([[6], [9], [12]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[ 1  3  6]
 [14 20  9]
 [ 5  6 12]]


# Numpy Joining Array
* Joining means putting contents of two or more arrays in single array.
* In SQL we join tables based on key,whereas in Numpy we join arrays by axes.
* We pass a sequence of arrays that we want to join to the concatenate() function,along with the axis.If axis is not explicity passed,it is taken as 0.

In [45]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [1]:
# 
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [3]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr2,arr1))
print(arr)

[4 5 6 1 2 3]


In [5]:
# 
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
a3=np.array([40,52,16])
arr=np.concatenate((arr1,a3,arr2))
print(arr)

[ 1  2  3 40 52 16  4  5  6]


In [7]:
#concatenating 2D arrays
import numpy as np
arr11 =np.array(range(1,7)).reshape(2,3)
print(arr11)
arr22 =np.array(range(1,11)).reshape(2,5)
print(arr22)
arr3=np.concatenate((arr11,arr22))
print(arr3)

[[1 2 3]
 [4 5 6]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 5

In [9]:
#concatenating 2D arrays
import numpy as np
arr11 =np.array(range(1,7)).reshape(2,3)
print(arr11)
arr22 =np.array(range(1,11)).reshape(2,5)
print(arr22)

print("**************")
arr3=np.concatenate((arr11,arr22),axis=1)
print(arr3)

[[1 2 3]
 [4 5 6]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
**************
[[ 1  2  3  1  2  3  4  5]
 [ 4  5  6  6  7  8  9 10]]


In [11]:

import numpy as np
arr11 =np.array(range(1,7)).reshape(2,3)
print(arr11)
arr22 =np.array(range(1,11)).reshape(2,5)
print(arr11)
arr3=np.concatenate((arr11,arr22),axis=0)
print(arr3)


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 5

In [13]:
import numpy as np
arr11 =np.array(range(1,16)).reshape(5,3)
print(arr11 )
arr22 =np.array(range(1,22)).reshape(7,3)
print(arr22)
print("*********")
arr3=np.concatenate((arr11,arr22),axis=0)
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]
*********
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


 # axis operating we performing that be diff or same allow but other must!!!!!!!! same
 

In [16]:
import numpy as np
arr11 =np.array(range(1,13)).reshape(2,3,2)
#print(arr11)
arr22 =np.array(range(13,25)).reshape(2,3,2)
#print(arr22)
arr3=np.concatenate((arr11,arr22),axis=0)

print(arr3)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


In [18]:
import numpy as np
arr11 =np.array(range(1,13)).reshape(2,3,2)
#print(arr11)
arr22 =np.array(range(13,25)).reshape(2,3,2)
#print(arr22)
arr3=np.concatenate((arr11,arr22),axis=1)# row 

print(arr3)
print(arr3.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [13 14]
  [15 16]
  [17 18]]

 [[ 7  8]
  [ 9 10]
  [11 12]
  [19 20]
  [21 22]
  [23 24]]]
(2, 6, 2)


In [20]:
import numpy as np
arr11 =np.array(range(1,13)).reshape(2,3,2)
#print(arr11)
arr22 =np.array(range(13,25)).reshape(2,3,2)
#print(arr22)
arr3=np.concatenate((arr11,arr22),axis=2)# col

print(arr3)
print(arr3.shape)


[[[ 1  2 13 14]
  [ 3  4 15 16]
  [ 5  6 17 18]]

 [[ 7  8 19 20]
  [ 9 10 21 22]
  [11 12 23 24]]]
(2, 3, 4)


In [22]:
import numpy as np
ar1 =np.array(range(10,61,10))
newa =np.array_split(ar1,2)
print(ar1)
print(newa)
#print(newa)

[10 20 30 40 50 60]
[array([10, 20, 30]), array([40, 50, 60])]


In [24]:
import numpy as np
ar1 =np.array(range(10,61,10))
newa =np.array_split(ar1,3)
print(ar1)
print(newa)

[10 20 30 40 50 60]
[array([10, 20]), array([30, 40]), array([50, 60])]


In [26]:
import numpy as np
ar1 =np.array(range(10,61,10))
newa =np.array_split(ar1,4)      # parting in 4 parting
print(ar1)
print(newa)

[10 20 30 40 50 60]
[array([10, 20]), array([30, 40]), array([50]), array([60])]


In [28]:
import numpy as np
ar1 =np.array(range(10,61,10))
newa =np.array_split(ar1,5)
print(ar1)
print(newa)

[10 20 30 40 50 60]
[array([10, 20]), array([30]), array([40]), array([50]), array([60])]


In [30]:
import numpy as np
ar1 =np.array(range(10,61,10))
newa =np.array_split(ar1,6)
print(ar1)
print(newa)

[10 20 30 40 50 60]
[array([10]), array([20]), array([30]), array([40]), array([50]), array([60])]


In [32]:
import numpy as np
ar1 =np.array(range(10,61,10))
newa =np.array_split(ar1,10)       # more 6  so make empty []
print(ar1)
print(newa)

[10 20 30 40 50 60]
[array([10]), array([20]), array([30]), array([40]), array([50]), array([60]), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32)]


In [34]:
import numpy as np
ar1 =np.array(range(10,81,10)).reshape(4,2)
#newa =np.array_split(ar1)
print(ar1)
#print(newa)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [36]:
import numpy as np
ar1 =np.array(range(10,81,10)).reshape(4,2)
newa =np.array_split(ar1,2)
print(ar1)
print("********")
print(newa)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]
********
[array([[10, 20],
       [30, 40]]), array([[50, 60],
       [70, 80]])]


In [38]:
import numpy as np
ar1 =np.array(range(10,81,10)).reshape(4,2)
newa =np.array_split(ar1,3)
print(ar1)
print("********")
print(newa)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]
********
[array([[10, 20],
       [30, 40]]), array([[50, 60]]), array([[70, 80]])]


In [40]:
a=[[10 ,20],[30 ,40],[50, 60],[70, 80]]
an=np.array_split(a,2)
for i in an:
    print(i)
    print("*****\n")

[[10 20]
 [30 40]]
*****

[[50 60]
 [70 80]]
*****



In [42]:
a=[[10 ,20],[30 ,40],[50, 60],[70, 80]]
an=np.array_split(a,3)
for i in an:
    print(i)
    print("*****\n")

[[10 20]
 [30 40]]
*****

[[50 60]]
*****

[[70 80]]
*****



In [44]:
a=[[10 ,20],[30 ,40],[50, 60],[70, 80]]
an=np.array_split(a,4)
for i in an:
    print(i)
    print("*****\n")

[[10 20]]
*****

[[30 40]]
*****

[[50 60]]
*****

[[70 80]]
*****



In [46]:
a=[[10 ,20],[30 ,40],[50, 60],[70, 80]]
an=np.array_split(a,2,axis=1)
for i in an:
    print(i)
    print("*****\n")

[[10 20]
 [30 40]
 [50 60]
 [70 80]]
*****

[]
*****



In [48]:
a=np.array([[10 ,20],[30 ,40],[50, 60],[70, 80]]).reshape(2,4)
#print(a)
an=np.array_split(a,2,axis=1)
for i in an:
    print(i)
    print("*****\n")

[[10 20]
 [50 60]]
*****

[[30 40]
 [70 80]]
*****



In [50]:
a=np.array([[10 ,20],[30 ,40],[50, 60],[70, 80]]).reshape(2,4)
#print(a)
an=np.array_split(a,3,axis=1)
for i in an:
    print(i)
    print("*****\n")

[[10 20]
 [50 60]]
*****

[[30]
 [70]]
*****

[[40]
 [80]]
*****



In [52]:
a=np.array([[10 ,20],[30 ,40],[50, 60],[70, 80]]).reshape(2,4)
#print(a)
an=np.array_split(a,3,axis=0)
for i in an:
    print(i)
    print("*****\n")

[[10 20 30 40]]
*****

[[50 60 70 80]]
*****

[]
*****



In [54]:
a=np.array(range(1,25)).reshape(4,2,3)
print(a)
print("*********************************************")
an=np.array_split(a,2,axis=1)
for i in an:
    print(i)
    print("*****\n")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]
*********************************************
[[[ 1  2  3]]

 [[ 7  8  9]]

 [[13 14 15]]

 [[19 20 21]]]
*****

[[[ 4  5  6]]

 [[10 11 12]]

 [[16 17 18]]

 [[22 23 24]]]
*****



In [56]:
a=np.array(range(1,25)).reshape(4,2,3)
print(a)
print("*********************************************")
an=np.array_split(a,2,axis=2)
for i in an:
    print(i)
    print("*****\n")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]
*********************************************
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]

 [[13 14]
  [16 17]]

 [[19 20]
  [22 23]]]
*****

[[[ 3]
  [ 6]]

 [[ 9]
  [12]]

 [[15]
  [18]]

 [[21]
  [24]]]
*****



In [58]:
a=np.array(range(1,25)).reshape(4,2,3)
print(a)
print("*********************************************")
an=np.array_split(a,3)
for i in an:
    print(i)
    print("*****\n")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]
*********************************************
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
*****

[[[13 14 15]
  [16 17 18]]]
*****

[[[19 20 21]
  [22 23 24]]]
*****



In [60]:
a=np.array(range(1,25)).reshape(4,2,3)
print(a)
print("*********************************************")
an=np.array_split(a,5)
for i in an:
    print(i)
    print("*****\n")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]
*********************************************
[[[1 2 3]
  [4 5 6]]]
*****

[[[ 7  8  9]
  [10 11 12]]]
*****

[[[13 14 15]
  [16 17 18]]]
*****

[[[19 20 21]
  [22 23 24]]]
*****

[]
*****



In [62]:
a=np.array(range(1,25)).reshape(2,6,2)   # ----> 2,6,2  2,2,2  2,2,2  2,1,2  2,1,2   axis=1,  split=4
print(a)
print("*********************************************")
an=np.array_split(a,4,axis=1)
for i in an:
    print(i)
    print("*****\n")

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]
  [19 20]
  [21 22]
  [23 24]]]
*********************************************
[[[ 1  2]
  [ 3  4]]

 [[13 14]
  [15 16]]]
*****

[[[ 5  6]
  [ 7  8]]

 [[17 18]
  [19 20]]]
*****

[[[ 9 10]]

 [[21 22]]]
*****

[[[11 12]]

 [[23 24]]]
*****



# Numpy Sorting Arrays


In [65]:
# true return not use bcz list method
import numpy as np
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [67]:
import numpy as np
arr=np.array([3,2,0,1])
print(np.sort(arr)[::-1])

[3 2 1 0]


In [69]:
import numpy as np
arr=np.array([[3,2,4],[5,0,1]])
print((arr))
print("------")
print(np.sort(arr))

[[3 2 4]
 [5 0 1]]
------
[[2 3 4]
 [0 1 5]]


In [71]:
import numpy as np
arr=np.array([[3,2,4],[5,0,1]])
print((arr))
print("------")
print(np.sort(arr,axis=0))

[[3 2 4]
 [5 0 1]]
------
[[3 0 1]
 [5 2 4]]


In [73]:
import numpy as np
arr=np.array([[3,2,4],[15,10,1],[30,21,4],[5,0,1]])
print((arr))
print("------")
print(np.sort(arr,axis=0))

[[ 3  2  4]
 [15 10  1]
 [30 21  4]
 [ 5  0  1]]
------
[[ 3  0  1]
 [ 5  2  1]
 [15 10  4]
 [30 21  4]]


In [75]:
import numpy as np
arr=np.array([[3,2,4],[15,10,1],[30,21,4],[5,0,1]])
print((arr))
print("------")
print(np.sort(arr,axis=1))

[[ 3  2  4]
 [15 10  1]
 [30 21  4]
 [ 5  0  1]]
------
[[ 2  3  4]
 [ 1 10 15]
 [ 4 21 30]
 [ 0  1  5]]


In [77]:
import numpy as np
arr=np.array([[[3,2,4],[15,10,1],[30,21,4],[5,0,1]]])
print((arr))
print("------")
print(np.sort(arr))

[[[ 3  2  4]
  [15 10  1]
  [30 21  4]
  [ 5  0  1]]]
------
[[[ 2  3  4]
  [ 1 10 15]
  [ 4 21 30]
  [ 0  1  5]]]


# Where function


In [80]:
import numpy as np
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==4)
print(x)


(array([3, 5, 6], dtype=int64),)


In [82]:
import numpy as np
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr%2==0)
print(x)


(array([1, 3, 5, 6], dtype=int64),)


In [84]:
import numpy as np
arr=np.array(range(1,13)).reshape(4,3)
print(arr)
x=np.where(arr==4)
print(x)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(array([1], dtype=int64), array([0], dtype=int64))


In [86]:
import numpy as np
arr=np.array(range(1,13)).reshape(4,3)
print(arr)
x=np.where(arr%2==0)
print(x)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(array([0, 1, 1, 2, 3, 3], dtype=int64), array([1, 0, 2, 1, 0, 2], dtype=int64))


In [88]:
import numpy as np
arr=np.array(range(5,76,5)).reshape(5,3)
print(arr)
x=np.where(arr%2==0)
print(x)



[[ 5 10 15]
 [20 25 30]
 [35 40 45]
 [50 55 60]
 [65 70 75]]
(array([0, 1, 1, 2, 3, 3, 4], dtype=int64), array([1, 0, 2, 1, 0, 2, 1], dtype=int64))


In [90]:
import numpy as np
arr=np.array(range(5,121,5)).reshape(4,2,3)
print(arr)
x=np.where(arr%2==0)
print(x)

[[[  5  10  15]
  [ 20  25  30]]

 [[ 35  40  45]
  [ 50  55  60]]

 [[ 65  70  75]
  [ 80  85  90]]

 [[ 95 100 105]
  [110 115 120]]]
(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3], dtype=int64), array([0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1], dtype=int64), array([1, 0, 2, 1, 0, 2, 1, 0, 2, 1, 0, 2], dtype=int64))


# Random

In [93]:
#1D
from numpy import random
x=random.randint(100)
print(x)


68


In [95]:
#1D
from numpy import random
x=random.randint(10)
print(x)

2


In [97]:
#Multi Dimension
from numpy import random
x=random.randint(100,size=(5))
print(x)


[85 21  3 49 10]


In [99]:
#3D Multi Dimension
from numpy import random
x=random.randint(100,size=(5,2,3))
print(x)

[[[59 12 63]
  [ 8 74 24]]

 [[57 73 61]
  [57 43 53]]

 [[34 35  2]
  [90 28 82]]

 [[94  9 57]
  [ 2 84 16]]

 [[88 50 61]
  [64 25 78]]]


In [101]:
from numpy import random
x=random.randint(500,size=(5,2,3))
print(x)

[[[291 192 235]
  [314 328 439]]

 [[253 298 279]
  [169 299 290]]

 [[324 276 396]
  [305 274 492]]

 [[ 18 234 452]
  [331 205 460]]

 [[146 170  34]
  [106  58 119]]]


In [103]:
from numpy import random
x=random.rand()
print(x)

0.09106517550656634


In [105]:
from numpy import random
x=random.rand(5)
print(x) #between 0 to 1 value give always give give floating point

[0.93806582 0.61460288 0.98160457 0.76045385 0.27841222]


In [107]:
from numpy import random
x=random.rand(5,3)
print(x)

[[0.98354488 0.08073224 0.49904041]
 [0.75434254 0.50765212 0.37163621]
 [0.58065407 0.54264395 0.75396337]
 [0.20419261 0.9688858  0.79559711]
 [0.42704058 0.22966706 0.43845213]]


In [109]:
from numpy import random
x=random.choice([3,5,7,9],size=(2,3))
print(x)


[[7 5 3]
 [3 5 3]]


In [111]:
class Vehicle:
    def __init__(self, name, mileage, seatingCapacity):
        self.name = name
        self.mileage = mileage
        self.seatingCapacity = seatingCapacity

    def fare(self):
        return self.seatingCapacity * 100


class Bus(Vehicle):
    def fare(self):
        total_fare = super().fare()          # normal fare
        maintenance = total_fare * 0.10      # 10% extra
        return total_fare + maintenance      # final fare

# -------- Example ----------
bus = Bus("Bus", 10, 50)
car = Vehicle("Car", 15, 5)

print("The bus seating capacity is", bus.seatingCapacity, ". so, the final fare amount should be", bus.fare())
print("The car seating capacity is", car.seatingCapacity, ". so, the final fare amount should be", car.fare())


The bus seating capacity is 50 . so, the final fare amount should be 5500.0
The car seating capacity is 5 . so, the final fare amount should be 500
