In [5]:
class Test:
    def __init__(self):
        self.x = 0
class Derived_Test(Test):
    def __init__(self):
        
        self.y = 1
def main():
     b = Derived_Test()
     print(b.x,b.y)
main()

AttributeError: 'Derived_Test' object has no attribute 'x'

In [9]:
class Test:
    def __init__(self):
        self.x = 0
class Derived_Test(Test):
    def __init__(self):
        super().__init__()
        self.y = 1
def main():
     b = Derived_Test()
     print(b.x,b.y)
main()

0 1


In [3]:
class Test:
    def __init__(self):
        self.x = 0
class Derived_Test(Test):
    def __init__(self):
        
        self.y = 1
def main():
     b = Derived_Test()
     print(b.y)
main()

1


In [13]:
class A():
    def disp(self):
        print("A disp()")
class B(A):
    pass
obj = B()
obj.disp()

A disp()


In [15]:
#546
class Test:
    def __init__(self):
        self.x = 0
class Derived_Test(Test):
    def __init__(self):
        Test.__init__(self)
        self.y = 1
def main():
    b = Derived_Test()
    print(b.x,b.y)
main()

0 1


In [21]:
class A:
    def one(self):
        return self.two()
 
    def two(self):
        return 'A'
 
class B(A):
    def two(self):
        return 'B'
obj1=A()
obj2=B()
print(obj1.two(),obj2.two())

A B


In [23]:
class A:
    def one(self):
        return self.two()
 
    def two(self):
        return 'A'
 
class B(A):
    def two(self):
        return 'B'
obj1=A()
obj2=B()
print(obj2.two(),obj1.two())

B A


In [39]:
class A:
    def __init__(self,x):
        self.x = x
    def count(self,x):
        self.x = self.x+1
class B(A):
    def __init__(self, y=0):
        A.__init__(self, 3) # x is 3 
        self.y = y
    def count(self):# overide
        self.y += 1     
def main():
    
    obj = B()
    obj.count()
    print(obj.x, obj.y)
main()

3 1


In [41]:
class A:
    def __init__(self,x):
        self.x = x
    def count(self,x):
        self.x = self.x+1
class B(A):
    def __init__(self, y=0):
        A.__init__(self, 3)
        self.y = y
    def count(self):
        super().count(None)
        self.y += 1     
def main():
    
    obj = B()
    obj.count()
    print(obj.x, obj.y)
main()

4 1


In [15]:
class Demo:
    def __init__(self):
        self.x = 1
    def change(self):
        self.x = 10
class Demo_derived(Demo):
    def change(self):
        self.x=self.x+1
        return self.x
def main():
    obj = Demo_derived()
    print(obj.change())
 
main()

2


In [19]:
class Demo:
    def __init__(self):
        self.x = 1
    def change(self):
        self.x = 10
class Demo_derived(Demo):
    def change(self):
        super().change()
        self.x=self.x+1
        return self.x
def main():
    obj = Demo_derived()
    print(obj.change())
 
main()

11


In [13]:
]

 Demo's check 
 Derived's check 


In [11]:
class A:
    def test1(self):
        print(" test of A called ")
class B(A):
    def test(self):
        print(" test of B called ")
class C(A):
    def test(self):
        print(" test of C called ")
class D(B,C):
    def test2(self):
        print(" test of D called ")        
obj=D()
obj.test()


 test of B called 


In [11]:
class People():
    def __init__(self, name):
      self.name = name
    def namePrint(self):
      print(self.name)
person1 = People("Sally")
person2 = People("Louise")
person1.namePrint()

Sally


In [13]:
person2.namePrint()

Louise


In [3]:
class A:
    def test1(self):
        print(" test of A called ")
class B(A):
    def test(self):
        print(" test of B called ")
class C(A):
    def test(self):
        print(" test of C called ")
class D(B,C):
    def test2(self):
        print(" test of D called ")        
obj=D()
obj.test()

 test of B called 


In [1]:
class A:
    def test2(self):
        print(" test of A called ")
class B(A):
    def test(self):
        print(" test of B called ")
class C(A):
    def test(self):
        print(" test of C called ")
class D(B,C):
    def test(self):
        print(" test of D called ")        
obj=D()
obj.test()

 test of D called 


In [25]:
#558
class Demo:
    def check(self):
        return " Demo's check "  
    def display(self):   # self refer to object
        print(self.check()) # demo.check
class Demo_Derived(Demo):
    def check(self):
        return " Derived's check "
Demo().display()
Demo_Derived().display()#inherited

 Demo's check 
 Derived's check 


In [15]:
# 559 
class A:
    def one(self):
        return self.two()            
    def two(self):  # overide
        return 'A'   
class B(A):
    def two(self): # overide
        return 'B'
obj2=B()     # object
print(obj2.two())

B


In [29]:
class A:
    def one(self):
        return self.two()            
    def two(self):
        return 'A'   
class B(A):
    def two(self):
        return 'B'
obj2=A()
print(obj2.two())

A


In [31]:
 import numpy as np
 a = np.array([1,2,3,5,8])
 print (a.ndim)

1


In [37]:
import numpy as np
a=np.array([1,2,3,4,5,6]) 
print(a)

[1 2 3 4 5 6]


In [39]:
import numpy as np
arr = np.array(42)
print(arr)

42


In [41]:
import numpy as np
arr = np.array([1, 2, 3, 4])#3 at index 2 
print(arr[2])

3


In [43]:
import numpy as np
arr = np.array([1, 2, -5, 4])#2 at -3 index from the end
print(arr[-3])

2


In [45]:
import numpy as np
arr = np.array([1, 2, -5, 4])
print(arr[-5])

IndexError: index -5 is out of bounds for axis 0 with size 4

In [49]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [19]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, -3])

8


In [57]:
import numpy as np    #0     #1    #2
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [59]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1, 1, 2])

12


In [61]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [63]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:-3])

[2 3 4]


In [65]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [67]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


In [71]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1,1,0:3])

[10 11 12]


In [77]:
import numpy as np                        #1  0to1  only 2 block   0:2 also work
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1,0:3])

[[7 8 9]]


In [79]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [81]:
import numpy as np  # 1 for 1 block 2 row 4 col
arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]]])
print(arr.shape)

(1, 2, 4)


In [83]:


import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [85]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)



[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [91]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [93]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [95]:
#582
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [97]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [99]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [101]:
import numpy as np
arr1 = np.array([[[1, 2], [3, 4]]])
arr2 = np.array([[[5, 6], [7, 8]]])
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [103]:
class A:
    def rk(self):
        print(" In class A")
class B:
    def rk(self):
        print(" In class B")
class C(A, B):
    def rk(self):
        pass
r = C()
print(C.__mro__)

(<class '__main__.C'>, <class '__main__.A'>, <class '__main__.B'>, <class 'object'>)


In [105]:
a=np.array([1,2,3,4])
print(a.shape)

(4,)


In [107]:
a=np.array([[1,2,3,4]])
print(a.shape)

(1, 4)


In [128]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(3, 3)
print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [126]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2,4)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]]


In [109]:
a=np.array([[[1,2,3,4]]])
print(a.shape)

(1, 1, 4)


In [136]:
#605
from abc import ABC,abstractmethod
class Father(ABC):
    @abstractmethod
    def display(self):
        pass
    def play(self):
        print('Abstract class')
class Son(Father):
    def play(self):
        print('Child class')
A=Son()
A.play()

TypeError: Can't instantiate abstract class Son with abstract method display

In [134]:
from abc import ABC,abstractmethod
class Father(ABC):
    @abstractmethod
    def display(self):
        pass
    def play(self):
        print('Abstract class')
class Son(Father):
    def display(self):
        print('Child class')
A=Son()
A.play()
A.display()

Abstract class
Child class


In [21]:
import numpy as np
arr1=np.array ([[1,3], [14,20], [5,6]])
arr2=np.array ([[6], [9], [12]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[ 1  3  6]
 [14 20  9]
 [ 5  6 12]]


In [27]:
#607
class A():
    def disp(self):
        print("C disp()")
class C():
    def disp(self):
        print("A disp()")        
class B(A,C):
    def dis(self):
        print("B disp()")      
obj = B()
obj.disp()

C disp()


In [29]:

class A():
    def disp(self):
        print("C disp()")
class C():
    def disp(self):
        print("A disp()")        
class B(A,C):
    def dis(self):
        print("B disp()")      
obj = B()
obj.dis()

B disp()


In [138]:
#608
class A:
    def __init__(self,x=3):
        self._x = x        
class B(A):
    def __init__(self):
        super().__init__(5)
    def display(self):
        print(self._x)
def main():
    obj = B()
    obj.display() 
main()

5


In [148]:
class A:
    def __init__(self,x=3):
        self._x = x        
class B(A):
    def __init__(self):
        super().__init__()
    def display(self):
        print(self._x)
def main():
    obj = B()
    obj.display() 
main()

3


In [150]:
class A:
    def __init__(self,x=3):
        self._x = x        
class B(A):
    def __init__(self):
        super().__init__(3)
    def display(self):
        print(self._x)
def main():
    obj = B()
    obj.display() 
main()

3


In [154]:
#609
class A:
    def __init__(self,x):
        self.x = x
    def count(self,x):
        self.x = self.x-2
class B(A):
    def __init__(self, y=0): #0-1    y=-1
        A.__init__(self, 3) # x=3
        self.y = y
    def count(self):
        self.y -= 1
def main():
    obj = B()
    obj.count()
    print(obj.x, obj.y)
main()

3 -1


In [156]:
class P:
    pass
class Q:
    pass
class R(P,Q):
    pass
class S(Q):
    pass     
class T(S,R):
    pass
a=T()
T.__mro__

(__main__.T, __main__.S, __main__.R, __main__.P, __main__.Q, object)

In [158]:
class Demo:
    def __init__(self):
        self.x = 1
    def change(self):
        self.x = 10
        return self.x
class Demo_derived(Demo):
    def change(self):
        self.x*=5
        return self.x
def main():
    obj = Demo_derived()
    print(obj.change())
main()

5


In [162]:
class Demo:
    def __init__(self):
        self.x = 1
    def change(self):
        self.x = 10
        return self.x
class Demo_derived(Demo):
    def change(self):
        super().change()
        self.x*=5
        return self.x
def main():
    obj = Demo_derived()
    print(obj.change())
main()

50


In [33]:
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
newarr = arr.reshape(4, 1, -1)
print(arr.shape)
print(newarr)

(3, 2, 2)
[[[ 1  2  3]]

 [[ 4  5  6]]

 [[ 7  8  9]]

 [[10 11 12]]]


In [35]:
import numpy as np

arr=np.array([[[1,2,3],
               [4,5,6]],
              
              [[7,8,9],
               [10,11,12]]])

arr1=np.array([[[4,3,2],
                [7,10,15]],

               [[6,1,2],
                [8,7,9]]])

newarr=np.concatenate((arr,arr1),axis=1)

print(newarr)#shape=(2,4,3)

x=newarr[:1:,:2:,:3:2]
print()
print(x)

y=np.sort(x)#by default row wise 
print()
print(y)

[[[ 1  2  3]
  [ 4  5  6]
  [ 4  3  2]
  [ 7 10 15]]

 [[ 7  8  9]
  [10 11 12]
  [ 6  1  2]
  [ 8  7  9]]]

[[[1 3]
  [4 6]]]

[[[1 3]
  [4 6]]]


In [168]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0:,-3:-2])

[[3]
 [8]]


In [172]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[6,5,3],[4,2,1]]])  # orginal ord (2,2,3)
x=arr[0:2,::2,::2]
print(x)
print(x.shape)

[[[1 3]]

 [[6 3]]]
(2, 1, 2)


In [37]:
import numpy as np
arr1 = np.array([[[1, 2], 
                  [3, 4]]])

arr2 = np.array([[[5, 6], 
                  [7, 8]]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)
print()
print(arr.shape)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]

(1, 4, 2)


In [174]:
class P1:
    def hi(self):
        print("hi  P1")
class P2:
    def hi(self):
        print("hi  P2")
class C1(P1):
        pass
class C2(P1):
    def hi(self):
        print("hello  C2")
class GC(C1,C2):
    pass
gc=GC()
gc.hi()

hello  C2


In [176]:
class P1:
    def hello(self):
        print("hi  P1")
class P2:
    def hi(self):
        print("hi  P2")
class C1(P1):
        pass
class C2(P1):
    def h(self):
        print("hello  C2")
class GC(C1,C2):
    pass
gc=GC()
gc.hello()

hi  P1


In [178]:
#620
class A:
    def __init__(self,  x=5):
        self.x = x
class der(A):
    def __init__(self, y=3):
        super().__init__()
        self.y = y
def main():
    obj = der()
    print(obj.x, obj.y)
main()

5 3


In [182]:
arr = np.array([1,2,3,4,5,6,7,8])
arr.reshape(2,4)
print(arr.ndim)

1


In [190]:
arr = np.array([1,2,3,4,5,6,7,8])
ar1=arr.reshape(2,4)
print(ar1)
print(ar1.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [198]:
import numpy as np
a=np.array([[5],[7],[8]])
b=np.array([[5,7,8]])
print("****a****")
print(a)
print("****b****")
print(b)
print("********")
print(b+a)

****a****
[[5]
 [7]
 [8]]
****b****
[[5 7 8]]
********
[[10 12 13]
 [12 14 15]
 [13 15 16]]


In [200]:
class A:
    def hello(self):
        print("1",end=",")
    def hello(self):
        print("2",end=",")
class B(A):
    def __init__(self):
        self.hello()
    def hello(self):
         print("3",end=",")
         super().hello()
b=B()# constructor init call 3,2,
b.hello() # explicit call 3,2,                                    #  final  3,2,3,2,

3,2,3,2,

In [202]:
# self.money += A.money takes the class variable value first for self.money and then adds A.money to it.

class A:
    money=5000 # class variable
    def __init__(self):
        self.money+=A.money
class B(A):
    def display(self):
        self.money+=2000
        print(self.money)
obj=B()
obj.display()

12000


In [204]:
class A:
    a=20
    def __init__(self):
        self.a+=10            # call init    +10
class B(A):
    a=15
    def buy(self):
        pass
class C(B,A):
    a=30                # found a 30      
    def buy(self):
        print(self.a)     # 30+=10
obj=C()
obj.buy()

40


In [206]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr[0, 1, : :-2]

array([6, 4])

In [208]:
import numpy as np
arr = np.array([[[1,2,3,4,5], [6,7,8,9,10]]])
print(arr[:,0, -3])

[3]


In [1]:
import numpy as np
arr1 = np.array([[[1, 2], [3, 4]]])
arr2 = np.array([[[5, 6], [7, 8]]])
arr = np.concatenate((arr1, arr2), axis=2)
print(arr)
print(arr.shape)

[[[1 2 5 6]
  [3 4 7 8]]]
(1, 2, 4)


In [3]:
arr = np.array([1,2,3,4,5,6,7,8])
arr.reshape(2,4)
print(arr.ndim)

1


In [18]:
arr1 = np.array([[1,2],[5,6]])
arr2 = np.array([[3,4],[7,8]])
arr=np.concatenate((arr1,arr2))
for i in arr:
 for j in i:
 
    if(j%2==0):
     newarr=j
print(newarr)

8


In [28]:
import numpy as np 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,]) 
x = np.where(arr%2 == 1)     # where give index
print(x)

(array([0, 2, 4, 6, 8, 9], dtype=int64),)


In [22]:
import numpy as np 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]) 
x = np.where(arr%2 == 0) 
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [9]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr1=np.array([[[4,3,2],[7,10,15]],[[6,1,2],[8,7,9]]])
newarr=np.concatenate((arr,arr1),axis=1)
print(newarr)
print("****************")
x=newarr[:1:,:2:,:3:2]

print("********x********")
print(x)

y=np.sort(x)
print("********y********")

print(y)

[[[ 1  2  3]
  [ 4  5  6]
  [ 4  3  2]
  [ 7 10 15]]

 [[ 7  8  9]
  [10 11 12]
  [ 6  1  2]
  [ 8  7  9]]]
****************
********x********
[[[1 3]
  [4 6]]]
********y********
[[[1 3]
  [4 6]]]


In [40]:
#606
import numpy as np
arr1=np.array ([[1,3], [14,20], [5,6]])
arr2=np.array ([[6], [9], [12]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr1.shape)
print(arr2.shape)
print(arr)

(3, 2)
(3, 1)
[[ 1  3  6]
 [14 20  9]
 [ 5  6 12]]


In [42]:
#603
import numpy as np
A=np.array([[[1,2], [4,3]], [[3,5], [6,4]]])
x=np.where(A==4)
print(x)

(array([0, 1], dtype=int64), array([1, 1], dtype=int64), array([0, 1], dtype=int64))


In [41]:
arr = np.array([[1, 2], 
                [3, 4], 
                [5, 4]])

x = np.where(arr == 4)
print(x)

(array([1, 2], dtype=int64), array([1, 1], dtype=int64))


In [43]:
arr = np.array([[1, 2], 
                [3, 4], 
                [4, 5]])

x = np.where(arr == 4)
print(x)

(array([1, 2], dtype=int64), array([1, 0], dtype=int64))


In [1]:
#598
import numpy as np
arr = np.array([True, False, True,0,1])
print(np.sort(arr))

[0 0 1 1 1]


In [3]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [9]:
import numpy as np
arr = np.array(k)
print(arr)

NameError: name 'k' is not defined

# 589

In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [6]:
arr = np.array([[1, 2], [3, 4],
                [5, 6], [7, 8],
                [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 6)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [10]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [12]:
arr = np.array([[1, 2], [3, 4], [5, 4]])
x = np.where(arr == 4)
print(x)

(array([1, 2], dtype=int64), array([1, 1], dtype=int64))


In [14]:
A=np.array([[[1,2],
             [4,3]], 
            [[3,5],
             [6,4]]])
x=np.where(A==4)
print(x)

(array([0, 1], dtype=int64), array([1, 1], dtype=int64), array([0, 1], dtype=int64))


# 616

In [23]:
arr1 = np.array([[[1, 2], [3, 4]]])
arr2 = np.array([[[5, 6], [7, 8]]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)
print("***************")

                     
print(arr.shape)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
***************
(1, 4, 2)


# 629

In [28]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], 
                [[7, 8, 9], [10, 11, 12]]])
arr[0, 1, : :-2]

array([6, 4])

# 631

In [39]:
import numpy as np
arr1 = np.array([[[1, 2], [3, 4]]])
arr2 = np.array([[[5, 6], [7, 8]]])
arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

print("***************")
print(arr.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
***************
(2, 2, 2)


In [41]:
import numpy as np
arr1 = np.array([[[1, 2], [3, 4]]])
arr2 = np.array([[[5, 6], [7, 8]]])
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

print("***************")
print(arr.shape)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
***************
(1, 4, 2)


In [43]:
import numpy as np
arr1 = np.array([[[1, 2], [3, 4]]])
arr2 = np.array([[[5, 6], [7, 8]]])
arr = np.concatenate((arr1, arr2), axis=2)

print(arr)

print("***************")
print(arr.shape)

[[[1 2 5 6]
  [3 4 7 8]]]
***************
(1, 2, 4)


In [3]:
class A():
    def disp(self):
        print("C disp()")
class C():
    def disp(self):
        print("A disp()")        
class B(A,C):
    def dis(self):
        print("B disp()")      
obj = B()
obj.disp()

C disp()


In [5]:
class A():
    def disp(self):
        print("C disp()")
class C():
    def disp(self):
        print("A disp()")        
class B(C,A):
    def dis(self):
        print("B disp()")      
obj = B()
obj.disp()

A disp()


In [11]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[6,5,3],[4,2,1]]])
x=arr[0:2,::2,::2]
print(x)
print(x.shape)

[[[1 3]]

 [[6 3]]]
(2, 1, 2)
